### ISSUE TITLE
No option appears in the context menu on Leia (Kodi 18)

### ISSUE THREAD

**Issue by RedSquirrel87** [Razzeee/context.trakt.contextmenu#3]
It seems that it does not work on Kodi 18 (Leia) since for me no new option appears in the context menu after installation.
If it could be useful, I solved this visibility issue simply by replacing "StringCompare" with "String.IsEqual" in the addon.xml file.

**Comment by razzeee** [comment]
Yes, the compare function was changed with v18 can you PR it?

**Comment by RedSquirrel87** [comment]
I hope I did well, it's the first time I do it xD
