### ISSUE TITLE
[Request] Hide/unhide show/season from progress

### ISSUE THREAD

**Issue by metaltermite** [Razzeee/context.trakt.contextmenu#5]
Currently, shows and seasons can be hidden from Trakt Progress Progress related web pages on the Trakt Dashboard. Shows and seasons can also be unhidden via trakt.tv/settings/hidden. It would be super convenient to have this built into the Kodi context menu.

- Hide show/season from Progress
- Unhide show/season from Progress

**Comment by razzeee** [comment]
Would need support in https://github.com/fuzeman/trakt.py/

And would best be tracked in https://github.com/trakt/script.trakt
